---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      # Only change these if you know what you're doing
      - PUID=1000
      - PGID=1000
      # Edit to match your current timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=UTC
      # Sets the listening port for the application. Defaults to 8083.
      # - CWA_PORT_OVERRIDE=8083
      # Hardcover API Key required for Hardcover as a Metadata Provider, get one here: https://docs.hardcover.app/api/getting-started/
      - HARDCOVER_TOKEN=your_hardcover_api_key_here
      # If your library is on a network share (e.g., NFS/SMB), disables WAL and chown to reduce locking/permission issues,
      # and switches file watching to polling (more reliable on network mounts) instead of inotify.
      # Accepts: true/false (default: false)
      - NETWORK_SHARE_MODE=false
      # If you want to force polling mode regardless of share type, set CWA_WATCH_MODE=poll
      # - CWA_WATCH_MODE=poll
      # Skip the automatic library detection/mount at startup. When enabled, the auto-library service will not run.
      # Accepts: true/yes/1 to disable auto-mount (default: false)
      # - DISABLE_LIBRARY_AUTOMOUNT=false
    volumes:
      - './config:/config'
      - './library:/calibre-library'
      - './ingest:/cwa-book-ingest'
    ports:
      # Change the first number to change the port you want to access the Web UI, not the second
      - 8083:8083
    # If you set CWA_PORT_OVERRIDE to a port below 1024, you may need to uncomment the following line:
    # cap_add:
    #   - NET_BIND_SERVICE
    restart: unless-stopped
