name: Post New Release Notes to Discord
# Automatically posts new Release Notes to the project's discord

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  github-releases-to-discord:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Releases To Discord
        uses: sillyangel/releases-to-discord@v1
        with:
          webhook_url: ${{ secrets.DISCORD_RELEASE_WEBHOOK_URL }}
          username: "CWA Release Changelog Bot"
          avatar_url: "https://github.com/crocodilestick/Calibre-Web-Automated/blob/main/README_images/cwa-logo-round-light.png"
